version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask_authentication_service
    environment:
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      FLASK_ENV: ${FLASK_ENV}
    command: 'flask run --host=0.0.0.0 --port=5000'
    ports:
      - 8000:5000
    networks:
      - auth_net
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - $PWD/.dbdata:/var/lib/postgres
    ports:
      - 5430:5432
    networks:
      - auth_net
  rabbitmq:
    image: rabbitmq:3.9.8-management-alpine
    ports:
      # AMQP protocol port
      - '5673:5672'
      # HTTP management UI
      - '15673:15672'
    networks:
      - auth_net
networks:
  auth_net:
    name: authentication_network