version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask_kafka_authentication_service
    environment:
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      FLASK_ENV: ${FLASK_ENV}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
    command: app/script/start_backend
#    command: 'flask run --host=0.0.0.0 --port=5000'
    ports:
      - 8000:5000
    networks:
      - auth_net
    volumes:
      - .:/app
    depends_on:
      - db
      - kafka
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - $PWD/.dbdata:/var/lib/postgres
    ports:
      - 5430:5432
    networks:
      - auth_net
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2182:2181
    networks:
      - auth_net
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9095:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - auth_net
networks:
  auth_net:
    name: authentication_network